version: '3'
services:
  api:
    build:
      context: ../taxi24
      dockerfile: ../docker/Dockerfile
    volumes:
      - ../taxi24:/code
    ports:
      - "8000:8000"
    env_file:
      - ../taxi24/.env
    depends_on:
      - db
  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: unrecano@recano.club
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taxi24db